apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::269172689858:user/go-backend-github-cli
      username: go-backend-github-cli
      groups:
        - system:masters
