name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: 12345
          POSTGRES_USER: root
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.24.2
        uses: actions/setup-go@v4
        with:
          go-version: ^1.24.2
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install golang-migrate CLI
        run: |
          go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.18.3
          echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Run DB migration
        run: make migrateup

      - name: Run tests
        run: make test
